-- MySQL Script generated by MySQL Workbench
-- Mwe 01 Uku 2019 21:57:34 CAT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema parts
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema parts
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `parts` ;
USE `parts` ;

-- -----------------------------------------------------
-- Table `parts`.`CarCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parts`.`CarCategory` (
  `idCarCategory` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `categoryName` VARCHAR(45) NULL,
  `categoryPart` VARCHAR(45) NULL,
  PRIMARY KEY (`idCarCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parts`.`SpareParts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parts`.`SpareParts` (
  `idSpareParts` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `namePart` VARCHAR(45) NULL,
  `locationPart` VARCHAR(45) NULL,
  `Phone` INT NULL,
  `price` INT NULL,
  PRIMARY KEY (`idSpareParts`),
  CONSTRAINT `
    idCarCategory`
    FOREIGN KEY ()
    REFERENCES `parts`.`CarCategory` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parts`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parts`.`customer` (
  `iduser` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fn` VARCHAR(45) NULL,
  `ln` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`iduser`),
  CONSTRAINT `idSpareParts`
    FOREIGN KEY ()
    REFERENCES `parts`.`SpareParts` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parts`.`Profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parts`.`Profile` (
  `idProfile` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  ` contact` INT NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`idProfile`),
  CONSTRAINT `user_id`
    FOREIGN KEY ()
    REFERENCES `parts`.`customer` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parts`.`Cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parts`.`Cart` (
  `idCart` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `active` TINYINT(1) NULL,
  `total` VARCHAR(45) NULL,
  PRIMARY KEY (`idCart`),
  CONSTRAINT `idProfile`
    FOREIGN KEY ()
    REFERENCES `parts`.`Profile` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `parts` ;

-- -----------------------------------------------------
-- Placeholder table for view `parts`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parts`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `parts`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parts`.`view1`;
USE `parts`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
